# Scaling & Combining

In [9]:
import numpy as np
import astropy
import ccdproc
from ccdproc import CCDData, Combiner
from astropy import units as u
from astropy.visualization import SqrtStretch
import matplotlib.pyplot as plt 
from matplotlib.colors import LogNorm
from photutils import centroid_com, centroid_1dg, centroid_2dg
from photutils import CircularAperture
from photutils import aperture_photometry
from photutils import Background2D
from photutils import MedianBackground
from scipy.ndimage import shift
import gc                                                           
gc.enable()

### <font color=purple> _Staring with V band_

In [14]:
# collecting shifted V band images and reading 
images = ccdproc.ImageFileCollection(".",glob_include='proc_NGC_2808_V_*')
scim = [CCDData.read(fn, unit = "adu") for fn in images.files_filtered(PICTTYPE = 1)]

INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
Set OBSGEO-Y to  2896022.315 from OBSGEO-[LBH].
Set OBSGEO-Z to -3889419.901 from OBSGEO-[LBH]'. [astropy.wcs.wcs]
Set OBSGEO-Y to  2896022.315 from OBSGEO-[LBH].
Set OBSGEO-Z to -3889419.901 from OBSGEO-[LBH]'.


INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]


INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.


INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]


INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.


INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]


INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.


INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]


INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.


INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO

INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.


: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]


INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.


INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]


INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.


INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]


INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.


INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]


INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.


INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]


INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.


INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]


INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.


INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]


INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.


INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]


INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.


INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]


INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.


INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]


INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.


INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]


INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.


INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]


INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.


INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO

INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.


: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]


INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.


INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]


INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.


INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]


INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.


INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]


INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.


In [16]:
# define the positions of some prominent stars in the image
positions = [(859,998), (349,783), (675,787),(570,622), (1085,549), (1237,558)]   #x-y notation
apertures = CircularAperture(positions, r=20.0)

In [17]:
# Complete aperture photometri for each image
phot_table=[]
for idx, thisimage in enumerate(scim): 
    phot_table.extend([aperture_photometry(thisimage, apertures)])
    print(idx, phot_table[idx])

0  id xcenter ycenter    aperture_sum    aperture_sum_err
      pix     pix          adu               adu       
--- ------- ------- ------------------ ----------------
  1   859.0   998.0  1431732.213414641              0.0
  2   349.0   783.0 1303607.0049587581              0.0
  3   675.0   787.0 1391505.1374854224              0.0
  4   570.0   622.0 1329839.5757741663              0.0
  5  1085.0   549.0 2049014.4610751367              0.0
  6  1237.0   558.0 1054799.2794533109              0.0
1  id xcenter ycenter    aperture_sum    aperture_sum_err
      pix     pix          adu               adu       
--- ------- ------- ------------------ ----------------
  1   859.0   998.0  1433276.040363774              0.0
  2   349.0   783.0 1300709.0711159455              0.0
  3   675.0   787.0 1388567.9142572442              0.0
  4   570.0   622.0  1337878.586269509              0.0
  5  1085.0   549.0  2056182.651859751              0.0
  6  1237.0   558.0 1052773.6935873833      

18  id xcenter ycenter    aperture_sum    aperture_sum_err
      pix     pix          adu               adu       
--- ------- ------- ------------------ ----------------
  1   859.0   998.0 1239023.7401090187              0.0
  2   349.0   783.0   1150553.68474233              0.0
  3   675.0   787.0 1213746.1918029343              0.0
  4   570.0   622.0 1172384.9499017925              0.0
  5  1085.0   549.0 1676783.9379572044              0.0
  6  1237.0   558.0  952019.7218895289              0.0
19  id xcenter ycenter    aperture_sum    aperture_sum_err
      pix     pix          adu               adu       
--- ------- ------- ------------------ ----------------
  1   859.0   998.0 1202085.3013354642              0.0
  2   349.0   783.0 1105008.2726931474              0.0
  3   675.0   787.0 1174862.8489478456              0.0
  4   570.0   622.0  1128248.165334804              0.0
  5  1085.0   549.0 1681313.8898105947              0.0
  6  1237.0   558.0   902703.435161736    

In [18]:
# the reference image for the V band will be the 1stimage
# here we are printing the counts and finding the median values
for idx, thisimage in enumerate(scim): 
    print(idx)
    print(phot_table[6]['aperture_sum']/phot_table[idx]['aperture_sum'])
    print(np.ma.median(phot_table[0]['aperture_sum']/phot_table[idx]['aperture_sum']))

0
[0.98757614 0.98005939 0.98357678 0.98330029 0.97372238 0.97454738]
1.0
1
[0.98651239 0.98224293 0.98565733 0.97739186 0.97032783 0.97642246]
1.000423457592539
2
[0.99045887 0.98402532 0.98928751 0.98384922 1.02569767 0.97835184]
1.0039752167869405
3
[0.99595033 0.99147411 0.99195524 0.98893348 0.98290623 0.98751612]
1.0089750266657211
4
[0.99534044 0.99552066 0.99605698 0.99422229 0.98453015 0.98542779]
1.011136030443298
5
[1.00038527 0.99987273 1.00443629 1.00209862 0.98919879 0.99607899]
1.0196670282336453
6
[1. 1. 1. 1. 1. 1.]
1.018664827105828
7
[1.00112865 0.99882906 0.99954036 0.99935131 1.03515183 0.99267857]
1.0174641717973536
8
[0.99968303 0.99587369 0.99478498 0.99815831 0.9896198  0.99552857]
1.0156232101262819
9
[1.00525892 1.00116427 1.00313048 1.00382803 0.98603977 0.99941427]
1.0203782818245966
10
[1.00667645 1.00117957 1.00236609 1.00365677 0.9851972  0.9959834 ]
1.0200213923443493
11
[1.00265403 0.99793045 1.0042149  0.99910165 0.98356565 0.99380382]
1.0171521948019

In [19]:
# scaling the images to our reference images
images = ccdproc.ImageFileCollection(".",glob_include = 'sproc_NGC_2808_V_*') #defines images
scim = [CCDData.read(fn) for fn in images.files_filtered()] #reads defined images
for idx, thisimage in enumerate(scim): 
    m = np.ma.median(phot_table[6]['aperture_sum'] / phot_table[idx]['aperture_sum'])
    print(m)
    scim[idx] = scim[idx].multiply(m * u.adu) 

sci_average = ccdproc.combine(scim, method = 'average',dtype = np.float32, 
                              minmax_clip = True, minmax_clip_min = -500) #calculating mean
sci_average.write("NGC_2808_V_average.fits")

sci_median = ccdproc.combine(scim, method = 'median',dtype = np.float32, 
                             minmax_clip = True, minmax_clip_min = -500) #calculating medians 
sci_median.write("NGC_2808_V_median.fits")

del(scim)
collected = gc.collect()
print('Check garbage collection', collected)

0.9816798402962046
0.9798173943706585
0.9866564141615429
0.9902037944374154
0.9947813614498613
1.0001290040314132
1.0
0.9994458330694227
0.9957011303174386
1.0021473716676543
1.0017728273738
0.9985160500450633
0.9979207990859267
1.0784414315713455
1.0956601054488324
1.096989671127274
1.1042096214187274
1.1053595932685614
1.1214933095634598
1.1619696165347557
1.1728923722270994
1.1843972450897295
1.0245703085142193
1.0137265662521513
1.0202099883420428
1.0400525327951886
1.0414946595259795
1.0566008556327064
1.0513831928330277
1.0511779789692335
Check garbage collection 232


### <font color=purple> _R band scale and combine_

In [20]:
# collecting processed R band images and reading into scim
images = ccdproc.ImageFileCollection(".",glob_include='proc_NGC_2808_R_*')
scim = [CCDData.read(fn, unit = "adu") for fn in images.files_filtered(PICTTYPE = 1)]

INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.


INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]


INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.


INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]


INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.


INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]


INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.


INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]


INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.


INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]


INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.


INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]


INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.


INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]


In [21]:
# define the positions of some prominent stars in the image
positions = [(864,999), (349,784), (675,790),(570,622), (1085,559), (1229,518)]   #x-y notation
apertures = CircularAperture(positions, r=20.0)

In [22]:
# Complete aperture photometry for each image
phot_table=[]
for idx, thisimage in enumerate(scim): 
    phot_table.extend([aperture_photometry(thisimage, apertures)])
    print(idx, phot_table[idx])

0  id xcenter ycenter    aperture_sum    aperture_sum_err
      pix     pix          adu               adu       
--- ------- ------- ------------------ ----------------
  1   864.0   999.0  1355392.642351546              0.0
  2   349.0   784.0  1350678.035339181              0.0
  3   675.0   790.0  1403193.311109228              0.0
  4   570.0   622.0 1298024.2413005068              0.0
  5  1085.0   559.0  1818662.568682152              0.0
  6  1229.0   518.0 1164266.0465822308              0.0
1  id xcenter ycenter    aperture_sum    aperture_sum_err
      pix     pix          adu               adu       
--- ------- ------- ------------------ ----------------
  1   864.0   999.0 1359954.5659341058              0.0
  2   349.0   784.0 1355206.6734113037              0.0
  3   675.0   790.0    1410175.7263627              0.0
  4   570.0   622.0 1298530.0636995472              0.0
  5  1085.0   559.0 1820630.4071101283              0.0
  6  1229.0   518.0  1163708.919101608      

19  id xcenter ycenter    aperture_sum    aperture_sum_err
      pix     pix          adu               adu       
--- ------- ------- ------------------ ----------------
  1   864.0   999.0 1364942.4024412236              0.0
  2   349.0   784.0 1365747.0059389775              0.0
  3   675.0   790.0  1409843.945680953              0.0
  4   570.0   622.0  1317314.656354962              0.0
  5  1085.0   559.0 1770767.2470958293              0.0
  6  1229.0   518.0 1201831.1626722855              0.0
20  id xcenter ycenter    aperture_sum    aperture_sum_err
      pix     pix          adu               adu       
--- ------- ------- ------------------ ----------------
  1   864.0   999.0 1375759.2980692415              0.0
  2   349.0   784.0 1366342.2542242322              0.0
  3   675.0   790.0  1415249.005885779              0.0
  4   570.0   622.0  1330035.996999019              0.0
  5  1085.0   559.0 1736387.5819133215              0.0
  6  1229.0   518.0  1225734.517444109    

In [23]:
# the reference image for the R band will be the 1st image
# here we are printing the counts and finding the median values
for idx, thisimage in enumerate(scim): 
    print(idx)
    print(phot_table[6]['aperture_sum']/phot_table[idx]['aperture_sum'])
    print(np.ma.median(phot_table[0]['aperture_sum']/phot_table[idx]['aperture_sum']))

0
[0.97914708 0.98417589 0.97920598 0.97927163 0.97935392 0.97738904]
1.0
1
[0.97586256 0.98088711 0.97435749 0.97889017 0.97829538 0.97785697]
0.9977887429255909
2
[0.9757941  0.9831833  0.97500094 0.97648877 0.97795953 0.9753543 ]
0.9975382084158841
3
[0.99181842 0.99603112 0.98983038 0.98975843 0.9876708  0.98960054]
1.0114479359653137
4
[0.98758492 0.99009852 0.98388639 0.98598273 0.98617509 0.9858334 ]
1.0069090608568936
5
[0.99385551 0.99865668 0.99327998 0.99378599 0.99390025 0.99274306]
1.0148372867206132
6
[1. 1. 1. 1. 1. 1.]
1.0212013608590742
7
[1.01155826 1.00911696 1.00969899 1.01118618 1.0123724  1.0097011 ]
1.0328248298469171
8
[1.01746907 1.01721153 1.0148949  1.0140183  1.01593137 1.01485369]
1.0368976729939452
9
[1.02817861 1.0272267  1.02195937 1.02606713 1.02471655 1.02447782]
1.0470524794975162
10
[1.03915371 1.04088658 1.03349736 1.03911755 1.03917094 1.04135451]
1.0610953598548125
11
[0.97361478 0.97802645 0.98243813 0.95887091 1.03830727 0.92872234]
0.9940507852

In [24]:
# scaling the images to our reference images
images = ccdproc.ImageFileCollection(".",glob_include = 'sproc_NGC_2808_R_*') #defines images
scim = [CCDData.read(fn) for fn in images.files_filtered()] #reads defined images
for idx, thisimage in enumerate(scim): 
    m = np.ma.median(phot_table[6]['aperture_sum'] / phot_table[idx]['aperture_sum'])
    print(m)
    scim[idx] = scim[idx].multiply(m * u.adu) 

sci_average = ccdproc.combine(scim, method = 'average',dtype = np.float32, 
                              minmax_clip = True, minmax_clip_min = -500) #calculating mean
sci_average.write("NGC_2808_R_average.fits")

sci_median = ccdproc.combine(scim, method = 'median',dtype = np.float32, 
                             minmax_clip = True, minmax_clip_min = -500) #calculating medians 
sci_median.write("NGC_2808_R_median.fits")

del(scim)
collected = gc.collect()
print('Check garbage collection', collected)

0.9792388058340389
0.9780761760225629
0.9761414324416458
0.9897944079634319
0.9860789104576431
0.9938207487208364
1.0
1.0104436441773739
1.0154131351124702
1.0253918407464373
1.0391623220447546
0.9758206149247337
0.9568741927507591
0.9678660695501607
0.960060281739227
0.9557952929721489
0.9661463959556429
0.9653756929570176
0.9706887922772138
0.9728067492840026
0.9677582654442543
Check garbage collection 228


### <font color=purple> _I band_

In [25]:
# collecting processed I band images and reading into scim
images = ccdproc.ImageFileCollection(".",glob_include='proc_NGC_2808_I_*')
scim = [CCDData.read(fn, unit = "adu") for fn in images.files_filtered(PICTTYPE = 1)]

INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.


INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]


INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.


INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]


INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.


INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]


INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.


INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]


INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.


INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]


INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.


INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]


INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.


INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]


INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.


INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]


In [26]:
# define the positions of some prominent stars in the image
positions = [(347,786), (623,796), (566,639),(1083,562), (1228,515), (1262,376)]   #x-y notation
apertures = CircularAperture(positions, r=20.0)

In [27]:
# Complete aperture photometri for each image
phot_table=[]
for idx, thisimage in enumerate(scim): 
    phot_table.extend([aperture_photometry(thisimage, apertures)])
    print(idx, phot_table[idx])

0  id xcenter ycenter    aperture_sum    aperture_sum_err
      pix     pix          adu               adu       
--- ------- ------- ------------------ ----------------
  1   347.0   786.0  625917.7902492008              0.0
  2   623.0   796.0 274346.77703536284              0.0
  3   566.0   639.0  483476.2751650661              0.0
  4  1083.0   562.0  672413.0636220854              0.0
  5  1228.0   515.0  459072.7355856062              0.0
  6  1262.0   376.0  638437.9825010813              0.0
1  id xcenter ycenter    aperture_sum   aperture_sum_err
      pix     pix          adu              adu       
--- ------- ------- ----------------- ----------------
  1   347.0   786.0  623229.099772279              0.0
  2   623.0   796.0 275761.5499961254              0.0
  3   566.0   639.0 487166.2469345518              0.0
  4  1083.0   562.0 673786.7353796719              0.0
  5  1228.0   515.0 464376.0741237472              0.0
  6  1262.0   376.0 637084.9282684759              0

20  id xcenter ycenter    aperture_sum   aperture_sum_err
      pix     pix          adu              adu       
--- ------- ------- ----------------- ----------------
  1   347.0   786.0 550754.9998020094              0.0
  2   623.0   796.0 259037.6085365598              0.0
  3   566.0   639.0 439648.0737171119              0.0
  4  1083.0   562.0 597804.4047619256              0.0
  5  1228.0   515.0 415393.1478948534              0.0
  6  1262.0   376.0 562692.4213095659              0.0
21  id xcenter ycenter    aperture_sum    aperture_sum_err
      pix     pix          adu               adu       
--- ------- ------- ------------------ ----------------
  1   347.0   786.0  542282.3118576758              0.0
  2   623.0   796.0 258936.55894852904              0.0
  3   566.0   639.0 430594.27707255527              0.0
  4  1083.0   562.0  581209.9718604431              0.0
  5  1228.0   515.0  413775.9228399392              0.0
  6  1262.0   376.0  555957.1902380605             

In [28]:
# the reference image for the R band will be the 1st image
# here we are printing the counts and finding the median values
for idx, thisimage in enumerate(scim): 
    print(idx)
    print(phot_table[0]['aperture_sum']/phot_table[idx]['aperture_sum'])
    print(np.ma.median(phot_table[0]['aperture_sum']/phot_table[idx]['aperture_sum']))

0
[1. 1. 1. 1. 1. 1.]
1.0
1
[1.00431413 0.99486958 0.99242564 0.99796127 0.98857965 1.00212382]
0.9964154224189978
2
[1.00226055 1.0078695  0.99357138 1.00337831 0.99639001 1.00345295]
1.0028194272007924
3
[1.00034496 0.9995126  0.99591073 0.99853352 0.9919414  1.00668054]
0.9990230568481301
4
[1.01922452 1.00645156 1.00420399 1.01831536 1.00914888 1.02499687]
1.0137321214497985
5
[1.01128759 1.00599271 0.99147504 0.99914913 0.99794394 1.00614385]
1.0025709219587466
6
[1.00697453 1.00610073 0.99944903 1.00335458 0.99937255 1.00121692]
1.002285747849737
7
[1.00473531 1.00677948 0.99904823 1.0040686  0.99044227 1.00815044]
1.004401954621645
8
[1.00493034 1.01122312 0.99164172 1.00357324 0.99502795 1.00591953]
1.0042517909016713
9
[1.1146654  1.02074491 1.0756216  1.10990108 1.0731198  1.11164641]
1.092761340946332
10
[1.11133046 1.00953501 1.08558201 1.11028508 1.06113819 1.10031657]
1.0929492909828944
11
[1.09688562 1.01554447 1.07822786 1.09497339 1.06487376 1.09215888]
1.0851933730306

In [29]:
# scaling the images to our reference images
images = ccdproc.ImageFileCollection(".",glob_include = 'sproc_NGC_2808_I_*') #defines images
scim = [CCDData.read(fn) for fn in images.files_filtered()] #reads defined images
for idx, thisimage in enumerate(scim): 
    m = np.ma.median(phot_table[6]['aperture_sum'] / phot_table[idx]['aperture_sum'])
    print(m)
    scim[idx] = scim[idx].multiply(m * u.adu) 

sci_average = ccdproc.combine(scim, method = 'average',dtype = np.float32, 
                              minmax_clip = True, minmax_clip_min = -500) #calculating mean
sci_average.write("NGC_2808_I_average.fits")

sci_median = ccdproc.combine(scim, method = 'median',dtype = np.float32, 
                             minmax_clip = True, minmax_clip_min = -500) #calculating medians 
sci_median.write("NGC_2808_I_median.fits")

del(scim)
collected = gc.collect()
print('Check garbage collection', collected)

0.9977205994763121
0.9937987290655439
0.9985196179446082
0.9943234364559294
1.0109738079577113
0.9992315674081478
1.0
1.0001368046677932
0.9990939514193924
1.0912024202412547
1.0925798311461625
1.0840553014977417
1.083411869759026
1.0684810527147683
1.0808642471333088
1.0868796165803447
1.1051687591794577
1.0907277956743573
1.2054116640994694
1.1501765396576726
1.113445053655943
1.1348324279197568
1.1426338179955549
1.1459653099263574
Check garbage collection 300
